install.packages("rJava")
install.packages("DBI")
install.packages("RJDBC")
install.packages("XML")
install.packages("memoise")
install.packages("KoNLP")
install.packages("wordcloud")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("ggmap")
install.packages("rvest")
install.packages("RColorBrewer")
install.packages("data.table")
install.packages("dplyr")
install.packages("reshape")
install.packages("stringr")
library(rJava)
library(DBI)
library(RJDBC)
library(XML)
library(memoise)
library(KoNLP)
library(wordcloud)
library(dplyr)
library(ggplot2)
library(ggmap)
library(rvest)
library(RColorBrewer)
library(data.table)
library(reshape) 
library(stringr)
getwd()
setwd("C:/R/project180721")
KoNLP::useSejongDic()
dseoulnew <- readLines("seoul_new.txt")
class(dseoulnew)
#명사추추
dseoulnew<-sapply(dseoulnew, extractNoun, USE.NAMES = T)
class(dseoulnew)
dseoulnew<-gsub("\\d+","",dseoulnew) #숮자제거
head(dseoulnew)
dseoulnew<-unlist(dseoulnew)
write(dseoulnew,"seoul_new2.txt")거 #공백제거

dseoulnew <- read.table("seoul_new2.txt")


wordcount <- table(unlist(nouns))
df <- as.data.frame(wordcount, stringsAsFactors = F)
df <- rename(df, word=Varl, freq=Freq)#
df <- filter(df,nchar(word) >= 2)

